kind: Service
apiVersion: v1
metadata:
  name: comment-db
spec:
  type: ClusterIP
  selector:
    app: reddit
    component: comment-db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
