apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-db
  labels:
    app: reddit
    component: post-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: post-db
  template:
    metadata:
      name: post-db
      labels:
        app: reddit
        component: post-db
    spec:
      containers:
        - name: post-db
          image: mongo:3.2
